#!/bin/sh
# This script will pull the necessary data from the slurm DB via the sacct command. The user must have sufficient privileges to call sacct as root via sudo
# NOTE: To add an additional month, copy & past a line and modify the start and end intervall (-S2017-01-01 -E2017-01-31) to that of the additional month

sudo sacct -n -P -S2017-01-01 -E2017-01-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_01.log 
sudo sacct -n -P -S2017-02-01 -E2017-02-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_02.log 
sudo sacct -n -P -S2017-03-01 -E2017-03-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_03.log 
sudo sacct -n -P -S2017-04-01 -E2017-04-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_04.log 
sudo sacct -n -P -S2017-05-01 -E2017-05-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_05.log 
sudo sacct -n -P -S2017-06-01 -E2017-06-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_06.log 
sudo sacct -n -P -S2017-07-01 -E2017-07-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_07.log 
sudo sacct -n -P -S2017-08-01 -E2017-08-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_08.log 
sudo sacct -n -P -S2017-09-01 -E2017-09-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_09.log 
DONE sudo sacct -n -P -S2017-10-01 -E2017-10-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_10.log 
sudo sacct -n -P -S2017-11-01 -E2017-11-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_11.log 
sudo sacct -n -P -S2017-12-01 -E2017-12-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2017_12.log 
sudo sacct -n -P -S2018-01-01 -E2018-01-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2018_01.log 
sudo sacct -n -P -S2018-02-01 -E2018-02-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2018_92.log 
sudo sacct -n -P -S2018-03-01 -E2018-04-31 --format JobIDRaw,Account,User,ReqCPUS,ReqMem,ReqNodes,AllocNodes,AllocCPUS,NNodes,NCPUS,NTasks,State,CPUTimeRAW,ElapsedRaw,TotalCPU,SystemCPU,UserCPU,MinCPU,AveCPU,MaxDiskRead,AveDiskRead,MaxDiskWrite,AveDiskWrite,MaxRSS,AveRSS,Submit,Start,Layout,ReqTRES,AllocTRES,ReqGRES,AllocGRES,Cluster,Partition > 2018_92.log 
